#! /bin/sh

#                  _            
#  _   _ _ __   __| | _____   __
# | | | | '_ \ / _` |/ _ \ \ / /
# | |_| | | | | (_| |  __/\ V / 
#  \__,_|_| |_|\__,_|\___| \_/  
# 
# my bspwm config
                       
# Init

xsettingsd &
sxhkd & # hotkeys
nitrogen --restore & # wallpaper
bash /home/mimi/.config/polybar/launch.sh # polybar 
mconnect &

# WM Options
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 30
bspc config top_padding 60
bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 14

bspc config focused_border_color "#f57c00"
bspc config normal_border_color "#f57c00"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false


